### ISSUE TITLE
Crash in Android due to Firebase

### ISSUE THREAD

**Issue by sampathk06** [sajanthomas01/react-native-jitsi-meet-extended#4]
When trying to integrate with my app, it is crashing on android with the following:

06-10 08:03:20.152 27172 27675 E AndroidRuntime: com.facebook.react.common.JavascriptException: Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.app().
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 
06-10 08:03:20.152 27172 27675 E AndroidRuntime: Ensure you have:
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 1) imported the 'io.invertase.firebase.app.ReactNativeFirebaseAppPackage' module in your 'MainApplication.java' file.
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 2) Added the 'new ReactNativeFirebaseAppPackage()' line inside of the RN 'getPackages()' method list.
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 
06-10 08:03:20.152 27172 27675 E AndroidRuntime: See http://invertase.link/android for full setup instructions., stack:
06-10 08:03:20.152 27172 27675 E AndroidRuntime: getAppModule@438:315
06-10 08:03:20.152 27172 27675 E AndroidRuntime: l@443:2197
06-10 08:03:20.152 27172 27675 E AndroidRuntime: getApp@443:281
06-10 08:03:20.152 27172 27675 E AndroidRuntime: A@444:1311
06-10 08:03:20.152 27172 27675 E AndroidRuntime: <unknown>@809:3772
06-10 08:03:20.152 27172 27675 E AndroidRuntime: h@2:1585
06-10 08:03:20.152 27172 27675 E AndroidRuntime: <unknown>@393:282
06-10 08:03:20.152 27172 27675 E AndroidRuntime: h@2:1585
06-10 08:03:20.152 27172 27675 E AndroidRuntime: <unknown>@6:91
06-10 08:03:20.152 27172 27675 E AndroidRuntime: h@2:1585
06-10 08:03:20.152 27172 27675 E AndroidRuntime: d@2:958
06-10 08:03:20.152 27172 27675 E AndroidRuntime: global code@1593:3
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
06-10 08:03:20.152 27172 27675 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
06-10 08:03:20.156 27172 27675 E JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR

Any ideas?

**Comment by sajanthomas01** [comment]
Not really but i have tried it with firebase in the past and was working for me, ill give it a shot again,

**Comment by sampathk06** [comment]
The issue was that our build had another index.bundle checked in which was being invoked instead of the Jitsi code. Removed that and this is working fine. Thanks.
